substitutions:
    devicename: tagreader
    upper_devicename: TagReader
  
  wifi:
    reboot_timeout: 10min
    networks:
    - ssid: 'IoT2'
      password: !secret wifi_password
  
  logger:
    baud_rate: 115200
  
  api:
  
  ota:
  
  esphome:
    name: "$devicename"
    platform: ESP8266
    esp8266_restore_from_flash: true
    board: d1_mini
    on_boot:
      priority: -10
      then:
      - globals.set:
          id: led_enable
          value: 'true'
  #    - output.turn_off:
  #        id: onboard_led
      - light.turn_on:
          id: activity_led
          brightness: 100%
          red: 30%
          blue: 100%
          green: 40%
      - delay: 200ms
      - light.turn_off:
          id: activity_led
      - delay: 150ms
      - light.turn_on:
          id: activity_led
          brightness: 100%
          red: 30%
          blue: 100%
          green: 40%
      - delay: 200ms
      - light.turn_off:
          id: activity_led
      - delay: 150ms
      - light.turn_on:
          id: activity_led
          brightness: 100%
          red: 30%
          blue: 100%
          green: 40%
      - delay: 200ms
      - light.turn_off:
          id: activity_led
      - delay: 150ms
      - light.turn_on:
          id: activity_led
          brightness: 100%
          red: 30%
          blue: 100%
          green: 40%
      - delay: 1000ms
      - light.turn_off:
          id: activity_led
  
  globals:
    - id: led_enable
      type: bool
  
  spi:
    clk_pin: D4
    miso_pin: D2
    mosi_pin: D3
  
  pn532:
    cs_pin: D1
    update_interval: 1s
    on_tag:
      then:
      - homeassistant.event:
          event: esphome.rfid_read
          data:
            device_id: tagreader  # this is the ESPHome device name in your ESPHome conf
          data_template:
            tag_id: !lambda "return x;"
      - if:      
          condition:
            lambda: "return id(led_enable);"
          then:
          - light.turn_on:
              id: activity_led
              brightness: 100%
              red: 35%
              blue: 100%
              green: 60%
          - delay: 500ms
          - light.turn_off:
              id: activity_led
      - delay: 2000ms
      - text_sensor.template.publish:
          id: rfid_tag
          state: 'waiting'
  
  light:
    - platform: fastled_clockless
      chipset: WS2811
      pin: D8
      default_transition_length: 10ms
      num_leds: 1
      rgb_order: GRB
      id: activity_led
      restore_mode: ALWAYS_OFF
      name: "Activity LED"
      internal: true
  
  #output:
  #  - platform: gpio
  #    pin: GPIO2
  #    id: onboard_led
  #    inverted: true
  
  switch:
    - platform: template
      name: "$upper_devicename LED enabled"
      restore_state: true
      lambda: |-
        if (id(led_enable)) {
          return true;
        } else {
          return false;
        }
      turn_on_action:
        - globals.set:
            id: led_enable
            value: 'true'
      turn_off_action:
        - globals.set:
            id: led_enable
            value: 'false'
  
  text_sensor:
    - platform: template
      name: "$upper_devicename Tag"
      id: rfid_tag
    - platform: homeassistant
      name: ha_state
      entity_id: sensor.rfid_tag