substitutions:
  devicename: tagreader
  upper_devicename: TagReader

web_server:
  port: 80

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

  on_boot:
    priority: -10
    then:
    - wait_until:
        api.connected:
    - logger.log: API is connected!
    - if:
        condition:
          lambda: "return id(beep_enable);"
        then:
        - output.esp8266_pwm.set_frequency:
            id: buzzer
            frequency: 500hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.esp8266_pwm.set_frequency:
            id: buzzer
            frequency: 750hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.esp8266_pwm.set_frequency:
            id: buzzer
            frequency: 1000Hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.turn_off: buzzer

switch:
- platform: template
  name: "Buzzer Enabled"
  id: beep_enable
  icon: mdi:volume-high
  optimistic: true
- platform: template
  name: "LED enabled"
  id: led_enable
  optimistic: true

#wifi insert your SSID and Your PWD once connected
wifi:
  ap:
    ssid: rfidreader
captive_portal:
# Enable logging
logger:
  baud_rate: 9600
# Enable Home Assistant API
api:
  password: !secret ESP_API_PWD
  services:
    - service: rfidreader_tag_ok
      then:
      - output.esp8266_pwm.set_frequency:
          id: buzzer
          frequency: 1000Hz
      - output.set_level:
          id: buzzer
          level: 50%
      - delay: 120ms
      - output.turn_off: buzzer

    - service: rfidreader_tag_ko
      then:
      - output.esp8266_pwm.set_frequency:
          id: buzzer
          frequency: 1Hz
      - output.set_level:
          id: buzzer
          level: 50%
      - delay: 250ms
      - output.turn_off: buzzer

ota:
  password: !secret ESP_OTA_PWD
spi:
  clk_pin: TX
  miso_pin: D1
  mosi_pin: D2

pn532:
  cs_pin: D3
  update_interval: 1s
  on_tag:
#TODO #3 - Add condition to read only once every 5 seconds
    then:
    - homeassistant.event:
        event: esphome.tag_scanned
        data:
          tag_id: !lambda 'return x;'
    - if:
        condition:
          lambda: "return id(led_enable);"
        then:
        - light.turn_on:
            id: activity_led
            brightness: 100%
            red: 0%
            green: 100%
            blue: 0%
        - delay: 500ms
        - light.turn_off:
            id: activity_led
    - if:
        condition:
          lambda: "return id(beep_enable);"
        then:
        - output.esp8266_pwm.set_frequency:
            id: buzzer
            frequency: 500hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.esp8266_pwm.set_frequency:
            id: buzzer
            frequency: 750hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.esp8266_pwm.set_frequency:
            id: buzzer
            frequency: 1000Hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 100ms
        - output.turn_off: buzzer
    - if:
        condition:
          switch.is_on: led_enable
        then:
        - light.turn_on:
            id: activity_led
            brightness: 100%
            red: 0%
            green: 100%
            blue: 0%
        - delay: 500ms
        - light.turn_off:
            id: activity_led

output:
- platform: esp8266_pwm
  pin: D8
  id: buzzer

light:
- platform: fastled_clockless
  chipset: WS2812
  pin: D7
  default_transition_length: 10ms
  num_leds: 1
  rgb_order: GRB
  id: activity_led
  restore_mode: ALWAYS_OFF
  name: "Activity LED"
  internal: true
