#!/usr/bin/env bash

set -e

echo "Getting mac address from device..."
mac=$(esptool.py read_mac | grep -m 1 'MAC:' | grep -o '.\{8\}$' )
mac=${mac//:/}

echo "MAC ending: ${mac}"

devicename="tagreader_${mac}"
upper_devicename="TagReader ${mac}"

esphome --substitution devicename "${devicename}" --substitution upper_devicename "${upper_devicename}" tagreader.yaml compile
esphome --substitution devicename "${devicename}" --substitution upper_devicename "${upper_devicename}" tagreader.yaml upload

rm -rf tagreader_${mac}

echo "Done tagreader_${mac}"
