#!/usr/bin/env bash

set -e

echo "Getting mac address from device..."
mac=$(esptool.py read_mac | grep -m 1 'MAC:' | grep -o '.\{8\}$' )
mac=${mac//:/}

echo "MAC ending: ${mac}"

sed -i "s/devicename: tagreader/devicename: tagreader_${mac}/" tagreader.yaml
sed -i "s/upper_devicename: TagReader/upper_devicename: TagReader ${mac}/" tagreader.yaml

esphome tagreader.yaml compile
esphome tagreader.yaml upload

sed -i "s/.${mac}//" tagreader.yaml

rm -rf tagreader_${mac}

echo "Done tagreader_${mac}"
